#this is a file that automates testing each time a code changes
name: CI #continuous integration

on: #this defines when the workflow will run. In this case, it runs on every push and pull request to the main branch.
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4 #this checks out the code from the repository so that it can be used in the workflow.
     
    - name: Set up Python #just a label for Github ui logs
      uses: actions/setup-python@v5 #uses Python instaler action to set up the Python environment
      with:
        python-version: '3.9'
    
    - name: Install dependencies
      run: pip install -r requirements.txt
    
    - name: Check Python version
      run: python --version